### ISSUE TITLE
Dead keys in DOSBox Staging

### ISSUE THREAD

**Issue by hanslse** [dosbox-staging/dosbox-staging#4509]
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### What operating system are you using?

Linux x86_64

### If other OS or Linux, please describe

Ubuntu 24.04.3 LTS

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

Asus E402N

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

The keys that represent ÅÄÖ in Swedish keyboard layout is "dead", in DOSBox, no matter what keyboard (Swedish, US, German, is set up. Nothing happens when these three keys  are pressed.  If I press and hold down the tilde key and then press either å, ä, or ö, the characters will be printed with a tilde. I am not sure if this is really a bug in DOSBox Staging, as I have no problem in my Raspberry Pi 3B, with the similar conf-file. It seems to be an issue with Ubuntu and DOSBox Staging. I have tested both the "auto" setting and the "sv" setting in the .conf-file, but the error persists. I have tested this on two laptops, the behaviour is the same, dead keys.

### Steps to reproduce the behaviour

Explain in detail how to reproduce the bug. Assume no familiarity with the software.
1. Install Ubuntu 24.04.3 LTS. Setup for Sweden, but with English language.
2. Install DOSBox Staging from Github. (The snap package on Snap, does not work- will not start)
3. Run DOSBox. press ÅÄÖ, no response with ÅÄÖ in DOSBox

### Your configuration

```ini
I am using the default .conf file without any changes.
```

### Provide a log

```text

```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

**Comment by FeralChild64** [comment]
Did you use the official stable binary from https://github.com/dosbox-staging/dosbox-staging/releases/tag/v0.82.2, or the current `main` branch build?

**Comment by Grounded0** [comment]
Finnish here. Ä, Ö, Å have been working fine for a few years.

Try typing `KEYB SV 850` and press enter. That should load Swedish keyboard layout with code page 850 that was used with Swedish.

**Comment by hanslse** [comment]
Yes!

Hans

Den 11 september 2025 18:53:59 CEST, FeralChild64 ***@***.***> skrev:
>FeralChild64 left a comment (dosbox-staging/dosbox-staging#4509)
>
>Did you use the official stable binary from https://github.com/dosbox-staging/dosbox-staging/releases/tag/v0.82.2, or the current `main` branch build?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/dosbox-staging/dosbox-staging/issues/4509#issuecomment-3281866547
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Hans Lindgren

**Comment by FeralChild64** [comment]
So I assume the problem is solved and we can close this issue?

**Comment by hanslse** [comment]
Hello!

Are you using Ubuntu 24.04.3 with the latest updates? The keys are even dead in US keyboard with the colons, semicolons and so on. The keyboard works well in DOSBox 0.74-3 based on SDL1. I suspect it is an issue with either Ubuntu or some libraries that DOSBox Staging uses. The same version of DOSBox Staging with the identical conf-file works well in Raspberry Pi 64-bit bookworm.

BR,
Hans

Den 11 september 2025 20:18:07 CEST, Grounded0 ***@***.***> skrev:
>Grounded0 left a comment (dosbox-staging/dosbox-staging#4509)
>
>Finnish here. Ä, Ö, Å have been working fine for a few years.
>
>Try typing `KEYB SV 850` and press enter. That should load Swedish keyboard layout with codepage 850 that was used with Swedish.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/dosbox-staging/dosbox-staging/issues/4509#issuecomment-3282142237
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Hans Lindgren

**Comment by hanslse** [comment]
It is not solved. What SDL2 libraries and other stuff is DOSBox Staging dependent in?
Will try to reinstall them, to see if this solves the problem?
BR,
Hans

Den 11 september 2025 20:31:21 CEST, FeralChild64 ***@***.***> skrev:
>FeralChild64 left a comment (dosbox-staging/dosbox-staging#4509)
>
>So I assume the problem is solved and we can close this issue?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/dosbox-staging/dosbox-staging/issues/4509#issuecomment-3282182205
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Hans Lindgren

**Comment by johnnovak** [comment]
> What SDL2 libraries and other stuff is DOSBox Staging dependent in?

Read the info on the Linux version download page:

https://www.dosbox-staging.org/releases/linux/#current-stable-version

Read this too, carefully, before you do anything else:

https://www.dosbox-staging.org/releases/linux/#non-official-repackaged-releases

Lastly, make sure to use the Linux binary downloaded from that page.

**Comment by hanslse** [comment]
I close this case, my conclusion is that my installation of Ubuntu 24.04.3 is most probably messed up and causes the problem, it is not a bug in DOSBox Staging.
